sudo: required
dist: trusty
language: cpp

services:
  - docker

before_install:
  - docker build -t DockerBuild -f dockerImage .

script: docker run DockerBuild /bin/bash -c "mkdir build-clang-debug && cd build-clang-debug && cmake .. && make -j$(nproc)"
